version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - ./server/db/initial-seed.sql:/docker-entrypoint-initdb.d/initial-seed.sql

  backend:
    build:
      context: ./server
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./front-end
    ports:
      - "3333:3333"

